# Generated by Django 5.0.2 on 2024-04-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_reportero_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportero',
            name='acta_nacimiento',
            field=models.FileField(blank=True, upload_to='actas/'),
        ),
        migrations.AddField(
            model_name='reportero',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
