# Generated by Django 5.0.6 on 2024-05-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_reportero_acta_nacimiento_reportero_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
